name: CD

on:
  push:
    # NOTE: Don't add other branches
    branches:
      - release

env:
  APP_TITLE: Miti
  GITHUB_WORKFLOW: true

jobs:
  test_build:
    if: github.event_name == 'push'
    name: Run Tests + Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Run pnpm install
        run: pnpm install

      - name: Build + Test
        run: pnpm build

      - name: Upload GH artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: build/
          name: client-build

  prod_deploy:
    name: Deploy
    needs: test_build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    permissions:
      contents: write
      id-token: write
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v2
